### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by ianschreuder** [alexgutteridge/rsruby#5]
Rsruby is not thread safe.
--
code:

require 'rsruby'
```Thread.new {
  rsruby = RSRuby.instance
  rsruby.rnorm(100)
}.join```

--
results in:

Error: C stack usage is too close to the limit
Error: C stack usage is too close to the limit
NoMethodError: R Function "get" not found
```    from /usr/local/ruby-1.9.2-p180.aba/lib/ruby/gems/1.9.1/gems/rsruby-0.5.1.1/lib/rsruby.rb:97:in `get_fun'
    from /usr/local/ruby-1.9.2-p180.aba/lib/ruby/gems/1.9.1/gems/rsruby-0.5.1.1/lib/rsruby.rb:97:in `reset_cache'
    from /usr/local/ruby-1.9.2-p180.aba/lib/ruby/gems/1.9.1/gems/rsruby-0.5.1.1/lib/rsruby.rb:85:in `initialize' 
    from /usr/local/ruby-1.9.2-p180.aba/lib/ruby/1.9.1/singleton.rb:109:in `new' 
    from /usr/local/ruby-1.9.2-p180.aba/lib/ruby/1.9.1/singleton.rb:109:in `block in instance' 
    from <internal:prelude>:10:in `synchronize' 
    from /usr/local/ruby-1.9.2-p180.aba/lib/ruby/1.9.1/singleton.rb:107:in `instance' 
    from (irb):3:in `block in irb_binding'
```

I suspect this is R's fault, but any insight you have would be appreciated.

Environment:
OS X - Lion and Snow Leopard
rsruby 0.5.1.1
R: 2.13.1

**Comment by rapofran** [comment]
thanks @aaronjg +1

**Comment by phikes** [comment]
Fix works, thanks! +1 for pulling that into the main repo.
